/**
 * Downloads the web fonts from Google Fonts and writes them into
 * public/fonts/ with a local @font-face stylesheet.
 *
 * Self-hosted rather than linked because:
 *   - a render-blocking third-party stylesheet delays first paint;
 *   - fonts linked from fonts.gstatic.com are unavailable offline, and this
 *     app has to work in a driveway with no signal;
 *   - Google Fonts logs the viewer's IP, which would be a third-party
 *     disclosure on both stores' privacy forms for no benefit.
 *
 * Run once, or again when the font stack in src/theme/tokens.ts changes:
 *   node scripts/fetch-fonts.mjs
 *
 * Output is committed. This is not part of the build.
 */
import { mkdirSync, writeFileSync } from 'node:fs';

const OUT_DIR = 'public/fonts';
const CSS_OUT = 'src/theme/fonts.css';

// Only the weights the design system actually uses; every extra weight is
// another file a phone downloads.
const FAMILIES = [
  'Inter+Tight:wght@400;500;600;700',
  // Display face. 300 is the design weight; 400 is kept for the few places a
  // heading sits on a photo, where 300 disappears into a light background.
  'Josefin+Sans:wght@300;400',
];

// Asking as a modern browser gets woff2 with unicode-range subsets.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const url =
    'https://fonts.googleapis.com/css2?' +
    FAMILIES.map((f) => `family=${f}`).join('&') +
    '&display=swap';

  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  let css = await res.text();

  const urls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]))];
  console.log(`${urls.length} font files referenced`);

  // Latin subsets only. The app is English-only; shipping Cyrillic and Greek
  // subsets would roughly triple the font payload for nothing.
  const wanted = [];
  const blocks = css.split('/*').filter(Boolean);
  const keepSubsets = new Set(['latin', 'latin-ext']);

  for (const url of urls) {
    const block = blocks.find((b) => b.includes(url));
    const subset = block?.split('*/')[0]?.trim() ?? 'latin';
    if (keepSubsets.has(subset)) wanted.push({ url, subset });
  }
  console.log(`keeping ${wanted.length} (latin, latin-ext)`);

  let downloaded = 0;
  for (const { url } of wanted) {
    const name = url.split('/').slice(-3).join('-');
    const file = `${OUT_DIR}/${name}`;
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    writeFileSync(file, buf);
    css = css.replaceAll(url, `/fonts/${name}`);
    downloaded++;
    console.log(`  ${name} ${(buf.length / 1024).toFixed(0)}KB`);
  }

  // Drop the @font-face blocks for subsets we did not download.
  css = css
    .split(/(?=\/\* )/)
    .filter((block) => !block.includes('https://fonts.gstatic.com'))
    .join('');

  const header =
    '/* GENERATED by scripts/fetch-fonts.mjs — do not edit.\n' +
    ' * Self-hosted so the app renders offline and makes no third-party\n' +
    ' * request. See docs/DECISIONS.md#0007. */\n\n';

  writeFileSync(CSS_OUT, header + css);
  console.log(`\n${downloaded} files -> ${OUT_DIR}`);
  console.log(`stylesheet -> ${CSS_OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
