/**
 * Generates src/theme/tokens.css from src/theme/tokens.ts.
 *
 * tokens.ts is the authority. This script exists so Tailwind and raw CSS can
 * read the same values the portable TS layer uses, without duplicating them —
 * and so the React Native port can consume tokens.ts directly with no CSS.
 *
 * Run: npm run tokens  (automatic before dev and build)
 */
import { writeFileSync, mkdirSync } from 'node:fs';

// Node >=22.18 strips TypeScript types on import, so tokens.ts is readable here
// with no build step and no loader.
const t = await import('../src/theme/tokens.ts');

const px = (n) => (typeof n === 'number' ? `${n}px` : n);

function schemeVars(scheme, indent = '  ') {
  return Object.entries(t.colour[scheme])
    .map(([k, v]) => `${indent}--c-${kebab(k)}: ${v};`)
    .join('\n');
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();

const lines = [];
lines.push('/* GENERATED by scripts/generate-tokens.mjs — do not edit.');
lines.push(' * Source of truth: src/theme/tokens.ts */');
lines.push('');

// Light is the base palette on bare :root, so no colour is defined only inside
// a media query. Dark overrides it twice: by preference, and by explicit opt-in.
lines.push(':root {');
lines.push(schemeVars('light'));
lines.push('');
for (const [k, v] of Object.entries(t.space)) lines.push(`  --space-${kebab(k)}: ${px(v)};`);
lines.push('');
for (const [k, v] of Object.entries(t.radius)) lines.push(`  --radius-${kebab(k)}: ${px(v)};`);
lines.push('');
for (const [k, v] of Object.entries(t.type)) lines.push(`  --font-${kebab(k)}: ${v};`);
lines.push('');
for (const [k, v] of Object.entries(t.textStyle)) {
  lines.push(`  --text-${kebab(k)}-size: ${px(v.size)};`);
  lines.push(`  --text-${kebab(k)}-leading: ${px(v.leading)};`);
  lines.push(`  --text-${kebab(k)}-tracking: ${v.tracking}em;`);
  lines.push(`  --text-${kebab(k)}-weight: ${v.weight};`);
}
lines.push('');
for (const [k, v] of Object.entries(t.motion)) {
  lines.push(`  --motion-${kebab(k)}: ${typeof v === 'number' ? `${v}ms` : v};`);
}
lines.push('');
for (const [k, v] of Object.entries(t.elevation)) lines.push(`  --shadow-${kebab(k)}: ${v};`);
lines.push('');
for (const [k, v] of Object.entries(t.layout)) lines.push(`  --layout-${kebab(k)}: ${px(v)};`);
lines.push('');
lines.push(`  --blur-glass: ${px(t.blur.glass)};`);
lines.push(`  --blur-glass-saturate: ${t.blur.glassSaturate}%;`);
lines.push('}');
lines.push('');

lines.push('/* System dark, unless the user explicitly chose light. */');
lines.push('@media (prefers-color-scheme: dark) {');
lines.push('  :root:not([data-theme="light"]) {');
lines.push(schemeVars('dark', '    '));
lines.push('  }');
lines.push('}');
lines.push('');
lines.push('/* Explicit dark wins in both directions. */');
lines.push(':root[data-theme="dark"] {');
lines.push(schemeVars('dark'));
lines.push('}');
lines.push('');

// Tailwind v4 reads its palette from @theme. Point it at the same variables
// rather than restating the values.
lines.push('@theme inline {');
for (const k of Object.keys(t.colour.light)) {
  lines.push(`  --color-${kebab(k)}: var(--c-${kebab(k)});`);
}
for (const [k] of Object.entries(t.radius)) lines.push(`  --radius-${kebab(k)}: var(--radius-${kebab(k)});`);
lines.push('  --font-display: var(--font-display);');
lines.push('  --font-body: var(--font-body);');
lines.push('}');
lines.push('');

mkdirSync('src/theme', { recursive: true });
writeFileSync('src/theme/tokens.css', lines.join('\n'));
console.log(`tokens.css written (${lines.length} lines)`);
